### PR TITLE
New update to prevent misunderstandings

### PR DESCRIPTION
**Pull request by wheelseal**
Line 463/464, line 467/467:
I'm starting here again because I think it's important for the user to avoid misunderstandings. I know that my changes will be long for one line. But what's wrong with buttons with multiple lines?

Line 472: small typo. Can you also put this hint in two lines. The current state doesn't look so good and especially disturbs the reading flow. For example:

Default settings for documents
         on this printer

In my opinion it is not a problem if the slide menu becomes bigger.

### CODE REVIEW

**Comment by attah** [comment]
Not easy to know, but changing the source phrase is not done in the .ts-files, especially just for one language. The source code itself needs changing, and then the .ts-files need to be updated, and translations probably need to be added back manually if they are to be kept. (This does not apply to translation ids like Jolla uses, but then even the primary language is a translation)

Anyway, about the content itself:

Regarding clear/reset... i am perhaps biased by the implementation, but i think it is important.
It refers to the saved default settings to be applied instead of any printer-supplied defaults for the same attributes.
I don't think clear and reset has a significant difference here really.
Resetting can mean to set to initial value, or to remove, which is correct - and to clear only means to remove, which is what it does.
So i prefer clear, albeit only slightly.

I don't think "my" adds anything - there are no others, so the implied these/current is fine.

About the line-break; is it maybe only needed for German? English looks more or less ok imo.

I think multiple lines will look really bad if it is just some menu items. If all selectable items or all hints are 2 lines, not as bad.

**Comment by attah** [comment]
I have added the "as", as per previous discussion.
After sleeping on it, i have changed to reset since it means the same thing. If it helps someone, good.
https://github.com/attah/harbour-seaprint/commit/76b219dc7cc7db7203b7301fb01a0cd607131a81
Thanks for spotting the typo.

**Comment by wheelseal** [comment]
Hi Attah, I send this yesterday as E-Mail to you. I don´t know how it is´t visible here. Did it arrived you?:

Thanks for your declaration of software development.

Clear/reset: I Agree with you that it is very important. And my favorite is reset because i think it is a bit more understandably for the user. Because i think Reset will be understand as to delete the changed setting (what you wrote) AND replace it with the defaults. Nice to talk with you about that. I don't want to get on your nerves with this.

Add "my": Was only a idea witch it can be more understandably by the user that your own saved settings are the default in the future. The Reset/Clear button (what ever you use) have no "my" in it.

About the line-break: I agree. German is longer and so it will look better in two lines. Is it a way to change it only for German?

Multiple lines: I agree. But this is only one menu of the hole app. We agree that the content is important. In my opinion more important as the design at this point.

I wish you and your family Merry Christmas an a happy new Y.ear

**Comment by attah** [comment]
No, i didn't get any email. I suggest you use github for comments.

I meant to say that not lying about implementation is important (regardless of users mental model), but as per my last comment i changed to reset.

I have line-broken the hint in German, but since i didn't go for any of the longer choices, they are still fine.
Hints actually look fine line-broken, but choices would look terrible. They don't need to be essays in help-text, users will figure it out if they try.

Thank you for thinking of my nerves.
Merry Christmas.

**Pull request closed without merging**
