### PR TITLE
Creation of the French locale

### PR DESCRIPTION
**Pull request by ensag-dev**
It seems like the About page is not localisable at the moment.

### CODE REVIEW

**Comment by Xray1870** [comment]
I will fix that asap.

**Comment by attah** [comment]
It should work now :)

**Comment by ensag-dev** [comment]
@attah many thanks! Should be 100% translated now!

**Comment by attah** [comment]
Thank you!

**Comment by ghost** [comment]
@ensag-dev Hi,

I like to ask you if you feel to translate my app Fileman also to French my French translator give it up.

That's why i ask.

Fileman is not into the Jolla Store becoss it using things that not's allowed there... It's only download able via OpenRepos.

Thanks!

Rudi

**Pull request merged**
