### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by JSEHV**
Dutch translation and ignore MacOS folder files (.DS_Store)

### CODE REVIEW

**Comment by attah** [comment]
Thank you! Unfortunately the file appears to be malformed. The translated string goes between the translation tags, not as the type attribute (which can be removed). See the other files for an example. I'd get around to moving it over eventually so it becomes mergable, but if you have time, i'd be happy for a fixed version.

**Comment by attah** [comment]
Fixed in #37 :)

**Comment by JSEHV** [comment]
Will check and fix it.

**Comment by attah** [comment]
No need, Rudi did it for us :)

**Pull request closed without merging**
