### PR TITLE
Update French

### PR DESCRIPTION
**Pull request by ensag-dev**

### CODE REVIEW

**Comment by attah** [comment]
Thank you! I'll update the release that is pending in store.

**Comment by attah** [comment]
Hi!

I'm writing this because you contributed translations in the past.
The next major version of SeaPrint is going live. Maybe already tomorrow.
There are a lot of new strings to be translated, so it is entirely understandable if you cannot find the time.
Deployment is going ahead anyway, but i will make new releases ~weekly as translations become complete.

Also, sorry for spamming.
If you want these kinds of updates in the future, watch this issue:
https://github.com/attah/harbour-seaprint/issues/29

Thanks!

**Comment by ensag-dev** [comment]
Hello! It's going to be a bit short for me :S

**Comment by attah** [comment]
I didn't mean to stress. I was trying to say: "take your time, and be aware i will deliver before translations are complete". In fact, i have already submitted it. There will probably be a release later this week, and next week etc. as translations are coming in. Take it when you have time, and thanks in advance.

**Pull request merged**
