### PR TITLE
Fixed a new path of argget.h for ppm2pwg in .pro file

### PR DESCRIPTION
**Pull request by sprainbrains**

### CODE REVIEW

**Comment by attah** [comment]
Thank you!
I do see you have some other commits.
Some good changes, some bad changes, some unnecessary, and some i don't understand.

Not only is the global find-replace on harbour- to ru.attah. broke a fair few things (repo link for one!), but you are also misrepresenting what this is.
If you really need this strange reverse uri notation that is popular nowadays, there is net.attah for that.
I'm not against changing for SFOS, but i'd need to check if changing package names is even allowed,

**Comment by sprainbrains** [comment]
> Thank you! I do see you have some other commits. Some good changes, some bad changes, some unnecessary, and some i don't understand.
> 
> Not only is the global find-replace on harbour- to ru.attah. broke a fair few things (repo link for one!), but you are also misrepresenting what this is. If you really need this strange reverse uri notation that is popular nowadays, there is net.attah for that. I'm not against changing for SFOS, but i'd need to check if changing package names is even allowed,

I should clarify a little bit.
The other branch is done by me for another Sailfish-based OS - Aurora OS. It has a number of specific requirements for translation, naming, icons style and etc.  
Calligra office has been removed as obsolete and libreoffice is used as a backend.

I will try to solve the Harbour-name-replaced issue.

All copyrights to your sources are left there.

**Comment by attah** [comment]
I'm well aware what Aurora is.
The more that can be cleanly upstreamed, the better for everyone.
I'm rewriting most of the actual IPP backed to not use Qt anymore... so any forks will be rather painful to maintain.

One problem i think you have is cramming way too much in the name - printer-info will contain massive amounts of text on some printers.
And Excel documents will probably produce very useless and unpredictable output (that's the entire point for filtering in the first place).

**Comment by sprainbrains** [comment]
> The more that can be cleanly upstreamed, the better for everyone.

yep. Agree

> I'm rewriting most of the actual IPP backed to not use Qt anymore... so any forks will be rather painful to maintain.

Thanks for it. Especially for clear and understandable code.

> One problem i think you have is cramming way too much in the name - printer-info will contain massive amounts of text on some printers.
> And Excel documents will probably produce very useless and unpredictable output (that's the entire point for filtering in the first place).

In my experience, there is enough information from employees at my work. No one has experienced any discomfort. 

Exel files have to be typed. We have gotten used to using styles and fonts from libreoffice for this and so when we need to print that through the sofffice utility converts well for printing. That's enough for us, so I put that in the code. 
I agree that it won't work for most people, it just fits under the needs at my job.

**Comment by attah** [comment]
> Thanks for it. Especially for clear and understandable code.

Thanks. Glad you see it that way. 

I guess i should look at dropping the excel filters and just warning users that they will get something unpredictable.
But for the name field(s); do share some examples (debug info preferably) of where your additions help, and i'll look if there can be generic logic that takes into account.

**Comment by sprainbrains** [comment]
> Thanks. Glad you see it that way.

Welcome)

 
> I guess i should look at dropping the excel filters and just warning users that they will get something unpredictable. But for the name field(s); do share some examples (debug info preferably) of where your additions help, and i'll look if there can be generic logic that takes into account.

Ok. Got it.
In my case, I using libreoffice backend, because OMP (owner Aurora OS) deleted all calligra office package from system. A little later OMP remove the calligra package from the repo as well. Libreoffice backend is default system package in OS now. It comes with the operating system image.

If it were not for these limitations, I would not have rewritten the code. But now, in my opinion, libreoffice is more perspective and produces excellent conversion results.

**Comment by attah** [comment]
The libreoffice integration is fine. It's some of the other parts that i don't get (printer names specifically).
Does it come with a (mobile) GUI? Are those sources available somewhere? Heck, maybe i could make it default to whatever exists if it is something i can install myself.

**Comment by sprainbrains** [comment]
> The libreoffice integration is fine. It's some of the other parts that i don't get (printer names specifically).
> Does it come with a (mobile) GUI? Are those sources available somewhere? Heck, maybe i could make it default to whatever exists if it is something i can install myself.

aaa finally got it)
I will prepare PR for part of code where I changed JS and C++ code for detection of printer name (or simply printer model series in other cases) .

**Pull request merged**
