### PR TITLE
German translation added

### PR DESCRIPTION
**Pull request by black-sheep-dev**
German translation added

Signed-off-by: Black Sheep <blacksheep@nubecula.org>

### CODE REVIEW

**Comment by attah** [comment]
Thank you very much!
I spotted a kopieren that should have been kopiert, i can fix that after merge.
PS And one of the (rather long-winded :) settings explanations is missing a translation. That's fine, but just pointing it out if it was unintentional. 
PPS i *think* process monochrome is process(-specific) monochrome, which might change the translation... (same for bi-level)

**Comment by attah** [comment]
Hi @black-sheep-dev 
Please let me know if you want to look at those details. 
If not i'll go ahead and merge. A 99% perfect German translation is certainly better than none.

**Comment by black-sheep-dev** [comment]
Hi @attah 
I will look at the details again.

**Comment by attah** [comment]
Thank you!

**Comment by black-sheep-dev** [comment]
You're welcome

**Pull request merged**
