### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by attah**
I need to make my mind up on licensing because I'll be linking with Poppler (and am thus limited to GPL).
@ruditimmer, @Karry @vigejolla - I believe you are the only ones with non-translation contributions. Thanks again for your contributions, and please speak now or forever hold your peace. :)

### CODE REVIEW

**Comment by Karry** [comment]
Hi. I'm fine with all (L)GPL licenses. My contribution is trivial I would be fine to provide it as public domain or under MIT :-)

Thank you for Seaprint!

**Comment by vigejolla** [comment]
> Hi. I'm fine with all (L)GPL licenses. My contribution is trivial I would be fine to provide it as public domain or under MIT :-)
> 
> Thank you for Seaprint!

Same here! :)

**Comment by attah** [comment]
Thank you very much for your replies (and contributions). I'll leave this open a bit longer (i'm way down in the memory debugging swamp anyway). Fairly certain @ruditimmer already suggested GPL3; but a documented ack would of course feel best.

**Comment by attah** [comment]
Merging.
Source for my comment in the previous post https://github.com/attah/harbour-seaprint/pull/4/commits/b7436cbb0d6a37ae423345e69d7e7be7d829602a

**Pull request merged**
